### PR TITLE
Fixed InvalidCastException thrown when querying for `Any` on a sqlite database

### LINKED ISSUE #42: InvalidCastException thrown when querying for `Any` on a sqlite database
Hi.

When I call the `Any` LINQ to Entities query on a sqlite database table with EFCache initialized, an `InvalidCastException` is thrown.

It can be reproduced using my fork here:
https://github.com/icnocop/EFCache

Compile and run the test `sqliteTest` (net462).

```
System.InvalidOperationException : The specified cast from a materialized 'System.Int64' type to the 'System.Boolean' type is not valid.
at System.Data.Entity.Core.Common.Internal.Materialization.Shaper.ErrorHandlingValueReader`1.GetValue(DbDataReader reader, Int32 ordinal)
   at lambda_method(Closure , Shaper )
   at System.Data.Entity.Core.Common.Internal.Materialization.Coordinator`1.ReadNextElement(Shaper shaper)
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<>c__14`1.<GetElementFunction>b__14_3(IEnumerable`1 sequence)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source, Expression`1 predicate)
   at EFCache.E2ETest.sqliteTest() in E:\github\icnocop\EFCache\test\EFCacheTests\E2ETest.cs:line 330
```

Any ideas?

Thank you.

### PR DESCRIPTION
**Pull request by icnocop**
Fixes #42

### CODE REVIEW

File: src/EFCache/CachingReader.cs [hunk 1]
```diff
@@ -56,7 +56,18 @@ public override int FieldCount
 
         public override bool GetBoolean(int ordinal)
         {
-            return (bool)GetValue(ordinal);
+            object value = GetValue(ordinal);
```
Comment (moozzyk) [inline src/EFCache/CachingReader.cs:59]:
```suggestion
            var value = GetValue(ordinal);
```

File: src/EFCache/CachingReader.cs [hunk 2]
```diff
@@ -56,7 +56,18 @@ public override int FieldCount
...
+            switch (value)
+            {
+                case bool boolValue:
+                    return boolValue;
+                case int intValue:
+                    return intValue != 0;
+                case long longValue:
+                    return longValue != 0;
+                default:
+                    throw new NotImplementedException($"{value.GetType()}");
```
Comment (moozzyk) [inline src/EFCache/CachingReader.cs:69]: The reason why I suggested blindly casting to `long` in the comment is that it will work with `byte`, `short` and other integral types. I don't think it makes sense to enumerate all these types here and I am fine with `InvalidCastException` for non-bool, non-integral values.

File: test/EFCacheTests/E2ETest.cs [hunk 3]
```diff
@@ -2,10 +2,18 @@
 
 namespace EFCache
 {
+#if NET462
```
Comment (moozzyk) [inline test/EFCacheTests/E2ETest.cs:5]: Consider grouping Sqlite usings and putting them at the end.

File: test/EFCacheTests/E2ETest.cs [hunk 4]
```diff
@@ -35,9 +43,18 @@ public class EntityMappedToSprocs
...
     {
-        static MyContext()
+        public MyContext()
+        {
+        }
+
+        public MyContext(string nameOrConnectionString)
+            : base(nameOrConnectionString)
+        {
+        }
```
Comment (moozzyk) [inline test/EFCacheTests/E2ETest.cs:53]: I think this is not used and can be removed.

File: test/EFCacheTests/E2ETest.cs [hunk 5]
```diff
@@ -48,6 +65,23 @@ static MyContext()
...
+            {
+                strategy = new SqliteDropCreateDatabaseAlways<MyContext>(modelBuilder);
+            }
+            else
+            {
+#endif
+                strategy = new DropCreateDatabaseAlways<MyContext>();
+#if NET462
+            }
+#endif
```
Comment (moozzyk) [inline test/EFCacheTests/E2ETest.cs:81]: Please extract a private method - this way you will be able to clean up the `ifdefs` and simplify passing the strategy (i.e. you no longer need a variable)

File: test/EFCacheTests/E2ETest.cs [hunk 6]
```diff
@@ -286,6 +320,41 @@ public void DbContext_GetCachingProviderServices_returns_correct_value()
             }
         }
 
+#if NET462
+        [Fact]
+        public void Query_Any_using_sqlite_returns_correct_value()
+        {
+            string tempFile = Path.GetTempFileName();
```
Comment (moozzyk) [inline test/EFCacheTests/E2ETest.cs:327]:
```suggestion
            var tempFile = Path.GetTempFileName();
```

File: test/EFCacheTests/E2ETest.cs [hunk 7]
```diff
@@ -286,6 +320,41 @@ public void DbContext_GetCachingProviderServices_returns_correct_value()
...
+
+            try
+            {
+                DbProviderFactory factory = DbProviderFactories.GetFactory("System.Data.SQLite.EF6");
```
Comment (moozzyk) [inline test/EFCacheTests/E2ETest.cs:331]:
```suggestion
                var factory = DbProviderFactories.GetFactory("System.Data.SQLite.EF6");
```

File: test/EFCacheTests/E2ETest.cs [hunk 8]
```diff
@@ -286,6 +320,41 @@ public void DbContext_GetCachingProviderServices_returns_correct_value()
...
+
+                using (DbConnection connection = factory.CreateConnection())
```
Comment (moozzyk) [inline test/EFCacheTests/E2ETest.cs:333]:
```suggestion
                using (var connection = factory.CreateConnection())
```

File: test/EFCacheTests/E2ETest.cs [hunk 9]
```diff
@@ -286,6 +320,41 @@ public void DbContext_GetCachingProviderServices_returns_correct_value()
...
+                {
+                    Assert.NotNull(connection);
```
Comment (moozzyk) [inline test/EFCacheTests/E2ETest.cs:335]: Consider removing? This is not part of test.

File: src/EFCache/CachingReader.cs (hunk 2 above)
Comment (icnocop) [reply src/EFCache/CachingReader.cs]: I have committed this change, but then the test `GetBoolean_converts_numeric_values_for_column` fails for the `int` column.

**Comment by icnocop** [comment]
Thank you for your review.
I have resolved all comments except for one which is causing a test to fail.

File: src/EFCache/CachingReader.cs (hunk 2 above)
Comment (moozzyk) [reply src/EFCache/CachingReader.cs]: I see. Probably because it's boxed. Don't worry about this then.

**Comment by icnocop** [comment]
Thank you.
All comments have been resolved.
